baseURL = "https://jarodl.am/"
languageCode = "en-us"
title = "Jarod Lam"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/jarodlam/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/jarod-lam/"}
  ]

[params]
  description = " "
  themeColor = "theme-base-0c"